### ISSUE TITLE
建议更名

### ISSUE THREAD

**Issue by Minemetero** [lingbopro/auto-close-netease-popup#1]
Change to 'bye to the f**k NetEase'

**Comment by lingbopro** [comment]
emmm

啊？？？

**Comment by Minemetero** [comment]
> emmm
> 
> 啊？？？

非常好听不是吗？

**Comment by lingbopro** [comment]
> > emmm
> > 
> > 啊？？？
> 
> 非常好听不是吗？

~~雀食~~  

不过仓库名里不能有`*`啊（

**Comment by Minemetero** [comment]
> > > emmm
> > > 啊？？？
> > 
> > 
> > 非常好听不是吗？
> 
> ~雀食~
> 
> 不过仓库名里不能有`*`啊（

那就不挡了

**Comment by Minemetero** [comment]
名字不个性一些谁会注意到啊

**Comment by Minemetero** [comment]
就比如 thefuck 由于名字所以被人注意

**Comment by Minemetero** [comment]
:)

**Comment by lingbopro** [comment]
> 就比如 thefuck 由于名字所以被人注意

呃啊  
这不太好罢（

**Comment by Minemetero** [comment]
> > 就比如 thefuck 由于名字所以被人注意
> 
> 呃啊 这不太好罢（

合适吗？实在太合适了！

**Comment by lingbopro** [comment]
> > > 就比如 thefuck 由于名字所以被人注意
> > 
> > 呃啊 这不太好罢（
> 
> 合适吗？实在太合适了！

改了，但是是描述  
仓库名还是不随便改了，容易发生某些意想不到的事情（GitHub官方解释）

**Comment by Minemetero** [comment]
> > > > 就比如 thefuck 由于名字所以被人注意
> > > 
> > > 
> > > 呃啊 这不太好罢（
> > 
> > 
> > 合适吗？实在太合适了！
> 
> 改了，但是是描述 仓库名还是不随便改了，容易发生某些意想不到的事情（GitHub官方解释）

ahhhhh
