### ISSUE TITLE
啊？

### ISSUE THREAD

**Issue by Minemetero** [lingbopro/auto-close-netease-popup#2]
let popup = document.getElementById("netease-promotion-modal"); //获取弹窗元素
        if(!(typeof(popup) == "undefined" || popup == null)) { //判断元素是否存在
            popup.remove(); //如果存在就去除
            console.log("成功去除网易弹窗~");
            return;
            
核心文件就这么一点？？？？？？？？

**Comment by lingbopro** [comment]
>         let popup = document.getElementById("netease-promotion-modal"); //获取弹窗元素
>         if(!(typeof(popup) == "undefined" || popup == null)) { //判断元素是否存在
>             popup.remove(); //如果存在就去除
>             console.log("成功去除网易弹窗~");
>             return;
>             
> 核心文件就这么一点？？？？？？？？

对，但是这个弹窗最近改版了，所以还得改一下

**Comment by lingbopro** [comment]
所以这个issue是不是可以关了（
